version: "3"
services:
  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: superpuper
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - 80:80
    environment:
      PGADMIN_DEFAULT_USER: postgres
      PGADMIN_DEFAULT_PASSWORD: superpuper
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  local_pgdata:
  pgadmin-data:
